version: '3.4'

services:

  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./dev/php.ini:/usr/local/etc/php/php.ini:ro
      - wp-files:/var/www/html:delegated
      - ./theme:/var/www/html/wp-content/themes/entourage:delegated
      - ./plugin:/var/www/html/wp-content/plugins/entourage:delegated
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: 2gmuBGvA
      #WORDPRESS_DEBUG: 1

  nginx:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./dev/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/etc/nginx/external:ro
      - wp-files:/var/www/html:ro
      - ./theme:/var/www/html/wp-content/themes/entourage:ro
      - ./plugin:/var/www/html/wp-content/plugins/entourage:ro
    depends_on:
      - wordpress

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2gmuBGvA
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql-data:/var/lib/mysql:delegated

  console:
    image: wordpress:cli
    volumes:
      - wp-files:/var/www/html:delegated
      - ./theme:/var/www/html/wp-content/themes/entourage:delegated
      - ./plugin:/var/www/html/wp-content/plugins/entourage:delegated
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: 2gmuBGvA

volumes:
  wp-files:
  mysql-data:
